version: '3'
services:
  db:
    image: postgres:15
    container_name: postgresql-shared-wallet-web
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'