app-config:
  wallets:
    - currency: 'Dollar'
      symbol: '$'
    - currency: 'Euro'
      symbol: '€'
    - currency: 'Toman'
      symbol: 'T'
  users:
    - username: 'Julia'
      password: 'JuliasPassword'
    - username: 'Jack'
      password: 'JacksPassword'